/**
 * Loan Identification — VA Loan Number and lender identifying information
 * Screen 2 of VA Form 26-8923
 * NOTE: This is the canonical version — the file was shown above in the chapters section.
 * Re-emitting here for completeness of the chapters directory.
 */
import React from 'react';
import {
  textUI,
  textSchema,
} from 'platform/forms-system/src/js/web-component-patterns';

export const loanIdentificationUiSchema = {
  loanIdentification: {
    'ui:title': 'Loan identification',
    vaLoanNumber: textUI({
      title: 'VA Loan Number',
      hint:
        'Enter the VA loan number for the existing VA-guaranteed loan being refinanced. This appears on the original loan closing documents.',
      inputType: 'text',
      autocomplete: 'off',
      errorMessages: {
        required: 'VA Loan Number is required.',
        pattern:
          'Enter a valid VA loan number (letters, numbers, and hyphens only, up to 14 characters).',
      },
    }),
    nameOfLender: textUI({
      title: 'Name of lender',
      hint:
        'Enter the full legal name of the VA-approved lending institution.',
      autocomplete: 'organization',
      errorMessages: {
        required: 'Name of lender is required.',
      },
    }),
    officerName: textUI({
      title: 'Officer name',
      hint:
        'Enter the full name of the lending institution officer who is certifying this worksheet.',
      autocomplete: 'name',
      errorMessages: {
        required: 'Officer name is required.',
      },
    }),
    officerTitle: textUI({
      title: 'Officer title',
      hint:
        "Enter the officer's title (for example, Vice President, Loan Officer).",
      autocomplete: 'organization-title',
      errorMessages: {
        required: 'Officer title is required.',
      },
    }),
    'view:signatureNotice': {
      'ui:description': () => (
        <va-additional-info
          trigger="Signature requirement for this form"
          uswds
        >
          <p>
            This form requires the signature and title of an officer of the
            lender, signed in ink on the printed form. The PDF generated by this
            tool must be printed and signed before inclusion in the IRRRL
            closing package, unless your institution has received VA
            authorization for electronic signature.
          </p>
        </va-additional-info>
      ),
    },
  },
};

export const loanIdentificationSchema = {
  type: 'object',
  properties: {
    loanIdentification: {
      type: 'object',
      required: ['vaLoanNumber', 'nameOfLender', 'officerName', 'officerTitle'],
      properties: {
        vaLoanNumber: {
          type: 'string',
          minLength: 1,
          maxLength: 14,
          pattern: '^[A-Za-z0-9\\-]+$',
        },
        nameOfLender: {
          type: 'string',
          minLength: 1,
          maxLength: 100,
        },
        officerName: {
          type: 'string',
          minLength: 1,
          maxLength: 100,
        },
        officerTitle: {
          type: 'string',
          minLength: 1,
          maxLength: 100,
        },
        'view:signatureNotice': {
          type: 'object',
          properties: {},
        },
      },
    },
  },
};